name: Bounteous.xUnit.Container.MsSql

on:
  pull_request:
    types: [ closed ]
    branches: [ main ]

jobs:
  publish:
    if: github.event.pull_request.merged == true
    uses: Bounteous-Inc/bounteous-dotnet-common-workflows/.github/workflows/build-and-publish-to-nuget.yml@main
    with:
      csproj-path: './src/Bounteous.xUnit.Container.MsSql/Bounteous.xUnit.Container.MsSql.csproj'
      nuget-package-name: 'Bounteous.xUnit.Container.MsSql'
      dotnet-version: '8.0.x'
      release-path: 'net8.0'
      build-configuration: 'Release'
    secrets:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      NUGET_SOURCE_URI: ${{ secrets.NUGET_SOURCE_URI }}